#!/usr/bin/env python
from game import Game

#def set_cur_color(color):
#    f, b = colors[color]
#    curses.init_pair(7, f, b)

class Control(object):
    def __init__(self, w, h, display):
        self.w = w
        self.h = h
        self.display = display
        self.reset()
        pass
    def move(self, color):
        self.game.move(color)
        return True
    def reset(self):
        self.game = Game(self.w, self.h, self.display)
        self.game.start()
        return True
    def quit(self):
        return False

def on_start(w, h, display):
    control = Control(w, h, display)
    display.loop(control)

import functools
import display
display.start( functools.partial(on_start, 5, 5) )

